# Generated by Django 2.0 on 2018-12-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('author', models.CharField(default='Anonymous', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_app.Question')),
            ],
        ),
    ]
